### PR TITLE
Added the features

### PR DESCRIPTION
**Pull request by Kritika75**
The following features has been added:

1. Category jokes
2. save the favourite jokes
3. save the favourite jokes from the previous visit
4. Clear the previous favourite jokes
5. Delete all the jokes
6. Repeat the last joke
7. Show your favourite ones
8. Exit, if nothing to input

### CODE REVIEW

**Comment by suryanshsk** [comment]
Yeah code works correctly

**Comment by Kritika75** [comment]
Ok,so can you please label my pr also close my issue if it is all fine

Thank you

**Comment by suryanshsk** [comment]
Sure, no problem.

**Comment by Kritika75** [comment]
Thank you, please label my pr also, with level tag and other suitable labels

**Comment by suryanshsk** [comment]
Done.

**Comment by Kritika75** [comment]
Thank you, I think you have to me one label only among 'label1, label2 and label3'

**Comment by suryanshsk** [comment]
Ok, I will do that.

**Pull request merged**
