### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by Aasthaa10**
made the description  more presentable and easy eye catcher And also added one more about this project to get the insights of technologies used

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@suryanshsk Add me as a collaborator to this project asap, I need to fix some labels here

**Comment by suryanshsk** [comment]
> @suryanshsk Add me as a collaborator to this project asap, I need to fix some labels here

PR already Merged

**Comment by MastanSayyad** [comment]
@suryanshsk Yes but I'm asking to add me as a collaborator to this project I have to fix the labels in some PRs in repository

can you explain on what basis you give `level 2` labels for such PR? with readme changes of only are you reviewing the code properly?

image

**Comment by suryanshsk** [comment]
Sorry but i can't give you access

**Comment by MastanSayyad** [comment]
Hi @suryanshsk Any particular reasons for not giving me the access? and I saw even after saying you haven't reduce the labels to this PR

**Comment by MastanSayyad** [comment]
@suryanshsk Bro Dont give such high labels to such PRs and issues, give only `level 1`, it is already mention that these type of repository can only have level 1 labels and not more, kindly reduce all levels to `level 1` for such PRs 

image

image

see your repo is full of spams 

image

Do you really think that people are this much talented that they created these apps in just few mins of time spans? this is just copy pasting, that's why I said not to give more than level 1.

image


see this

issue was created 35 mins ago

image

and for the same issue get created PR in just 10-20 mins? and he created 3-4 PRs in this 30 min time span, is it possible for a developer? I request you to please review the code properly

image

### **And Please add me as a collaborator asap.**

**Comment by MastanSayyad** [comment]
@suryanshsk Are you there?

**Comment by MastanSayyad** [comment]
@suryanshsk Your repo is full of spam and inappropriate labeling! I need explanation why are you not responding even when you are active on your repo?

**Comment by suryanshsk** [comment]
> @suryanshsk Your repo is full of spam and inappropriate labeling! I need explanation why are you not responding even when you are active on your repo?

Hi Mastan,

Thank you for reaching out and for your patience.

Apologies for the delay in my response. I understand your concerns about the labeling and spam issues within the repository. After reviewing the feedback, I agree that some PRs may not reflect the effort deserving of higher labels, and I will work on correcting that by adjusting the labels to level 1 where appropriate.

Regarding the spammy submissions, I will also take your suggestion to ensure the code is thoroughly reviewed before merging and be more vigilant about PRs that may have been copy-pasted. Moving forward, I’ll implement stricter review guidelines to ensure that only quality contributions are rewarded.

I will also add you as a collaborator to help manage the repository, as you suggested. Your insights will be extremely valuable in improving the quality of the contributions.

Thanks again for your understanding, and I appreciate your help in maintaining the integrity of the project.

**Comment by suryanshsk** [comment]
> Hi @suryanshsk Any particular reasons for not giving me the access? and I saw even after saying you haven't reduce the labels to this PR

Hi Mastan,

Apologies for the confusion. I didn’t realize you are the Program Manager because I’ve been receiving several requests from contributors asking to be added as collaborators. In the process, I mistakenly treated your request the same way. Unfortunately, I can't grant access in this case, but I truly appreciate your involvement and feedback.

Thank you for understanding, and I hope we can continue collaborating effectively.

Best regards,
Suryansh

**Comment by MastanSayyad** [comment]
@suryanshsk No problem, thank you for adding me as a collaborator

**Comment by suryanshsk** [comment]
> @suryanshsk Bro Dont give such high labels to such PRs and issues, give only `level 1`, it is already mention that these type of repository can only have level 1 labels and not more, kindly reduce all levels to `level 1` for such PRs
> 
> image
> 
> image
> 
> see your repo is full of spams
> 
> image
> 
> Do you really think that people are this much talented that they created these apps in just few mins of time spans? this is just copy pasting, that's why I said not to give more than level 1.
> 
> image
> 
> see this
> 
> issue was created 35 mins ago
> 
> image
> 
> and for the same issue get created PR in just 10-20 mins? and he created 3-4 PRs in this 30 min time span, is it possible for a developer? I request you to please review the code properly
> 
> image
> 
> ### **And Please add me as a collaborator asap.**

I also thought the same thing How can they Submit Pr un just 10-20 min. I thought to close The PR because they use Chat GOT but according to guidelines they submit issue and PR ,  I can't close that but after your message now I'm able to do it . And also one thing many contributors try to create unnecessary Issues and i closed their issues, Can i do it?

**Comment by MastanSayyad** [comment]
Yes. feel free to close all unnecessary issues @suryanshsk

**Comment by suryanshsk** [comment]
Oh, Thank you so much

**Pull request merged**
