### PR TITLE
Book Recommendation System

### PR DESCRIPTION
**Pull request by SimranShaikh20**
Issue no - #432 

i have added entire folder including all mandatory files.
@suryanshsk is there any confilcts let me know !

### CODE REVIEW

**Comment by suryanshsk** [comment]
This is  not related with our projects

**Comment by SimranShaikh20** [comment]
> This is not related with our projects

@suryanshsk but i had mentioned entire description in issue!

**Comment by SimranShaikh20** [comment]
> This is not related with our projects

According to that what changes I have to make

**Comment by SimranShaikh20** [comment]
@suryanshsk can you please change level as it include one entire important concept !

**Comment by SimranShaikh20** [comment]
@suryanshsk  can you please change level !

**Comment by suryanshsk** [comment]
Your issue is related to level 1 according to GSSoC Guidelines

**Pull request merged**
