### PR TITLE
Fix: add-contributor.yml garbage commits

### PR DESCRIPTION
**Pull request by yashksaini-coder**
✅ Fixes: #155

This PR removes the unnecessary parameters from the `Update Contributors List` job. that were initially used in the config list. It should run automatically on the **main** branch.

Workflow trigger updates:

* [`.github/workflows/add-contributor.yml`](diffhunk://#diff-f11b4db8ec4e64c191e5b311659ac5e7cd4ef61a72741f404b8cbb537bdd13c5L5-R5): Restricted the workflow to trigger only on pushes to the `main` branch.

Job configuration simplification:

* [`.github/workflows/add-contributor.yml`](diffhunk://#diff-f11b4db8ec4e64c191e5b311659ac5e7cd4ef61a72741f404b8cbb537bdd13c5L23-L26): Removed the `commit_message`, `committer_username`, and `committer_email` parameters from the `Update Contributors List` job, simplifying the configuration.

### CODE REVIEW

**Comment by yashksaini-coder** [comment]
@wizaye can you review this and add labels to it. 

the changes i made were simple to remove the extra branches where the cron job was executing, and also to remove the extra parameter that I thought were necessary.

**Comment by wizaye** [comment]
@yashksaini-coder for sure! , can you just give me time till EOD I'm working on 2 on going prs for the repo right now. I'll check once I'm done with these.

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder for sure! , can you just give me time till EOD I'm working on 2 on going prs for the repo right now. I'll check once I'm done with these.

no problem, @wizaye

**Comment by yashksaini-coder** [comment]
also here's the referenced issue, https://github.com/suryanshsk/Python-Voice-Assistant-Suryanshsk/issues/155

can you assign me this issue as I have raised a PR for this and also add proper labels of `gssoc` & `hacktoberfest`

**Comment by wizaye** [comment]
@yashksaini-coder the code is much cleaner now. Kudos for faster response on mentioning, hope this will continue till end of hacktober to improve the product as well. As far for the labels only @suryanshsk  can add the labels as he is the owner and no one else can.

**Pull request merged**
