### PR TITLE
Additon of a navigation tool 

### PR DESCRIPTION
**Pull request by Chin-may02**
1. Offering shortest path
2. Works on constant feedback system
3. Great UI

### CODE REVIEW

**Comment by Chin-may02** [comment]
Could you please add the right tags 
gssoc-ext,  hacktoberfest-accepted and the level-2 tag

**Comment by suryanshsk** [comment]
Fixed!

**Comment by Chin-may02** [comment]
Even here do please add the labels it would mean a lot thank you

**Comment by Chin-may02** [comment]
This was tagged as a level 2 in issues could you please check

**Pull request merged**
